/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Metadata {
  htmlElements: ElementsData;
  ch5Elements: ElementsData;
}
export interface ElementsData {
  common: CommonData;
  elements?: Ch5Element[];
}
export interface CommonData {
  exclude?: string[];
  attributes: Ch5Attribute[];
}
export interface Ch5Attribute {
  name: string;
  value?: string[];
  documentation?: string[];
}
export interface Ch5Element {
  // document?: string;
  // ctime?: string;
  name: string;
  tagName: string;
  description?: string;
  attributes?: Ch5Attribute[];
  documentation?: string[];
  snippets?: Ch5Snippet[];
}
export interface Ch5Snippet {
  prefix: string;
  description: string;
  body: string[];
}
