/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Metadata {
  version: string;
  htmlElements: ElementsData;
  ch5Elements: ElementsData;
  [k: string]: any;
}
export interface ElementsData {
  common: CommonData;
  elements?: Ch5Element[];
  [k: string]: any;
}
export interface CommonData {
  exclude?: string[];
  attributes: Ch5Attribute[];
  [k: string]: any;
}
export interface Ch5Attribute {
  name: string;
  value?: string[];
  documentation?: string[];
  default?: string;
  deprecated?: Deprecated;
  [k: string]: any;
}
export interface Deprecated {
  version?: string;
  descriptions?: string;
  [k: string]: any;
}
export interface Ch5Element {
  name: string;
  tagName: string;
  description?: string;
  attributes?: Ch5Attribute[];
  documentation?: string[];
  snippets?: Ch5Snippet[];
  childElements?: ChildElements[];
  role?: string;
  componentVersion?: string;
  [k: string]: any;
}
export interface Ch5Snippet {
  prefix: string;
  description: string;
  body: string[];
  [k: string]: any;
}
export interface ChildElements {
  tagName?: string;
  optional?: boolean;
  childElements?: ChildElements[];
  [k: string]: any;
}
