// Copyright (C) 2018 to the present, Crestron Electronics, Inc.
// All rights reserved.
// No part of this software may be reproduced in any form, machine
// or natural, without the express written consent of Crestron Electronics.
// Use of this source code is subject to the terms of the Crestron Software License Agreement
// under which you licensed this source code.

export const ch5Attributes = [
    "change",
    "customClass",
    "customStyle",
    "dirty",
    "disabled",
    "iconClass",
    "handleShape",
    "iconPosition",
    "id",
    "feedbackMode",
    "focus",
    "keyPress",
    "label",
    "labelOn",
    "labelOff",
    "mask",
    "maxValue",
    "minLength",
    "minValue",
    "noShowType",
    "orientation",
    "placeholder",
    "previewColor",
    "receiveStateBluenValue",
    "receiveStateEnable",
    "receiveStateFocus",
    "receiveStateGreenValue",
    "receiveStateScriptLabelHtml",
    "receiveStateRedValue",
    "receiveStateShow",
    "receiveStateValue",
    "scaling",
    "sendEventColorBlueOnChange",
    "sendEventColorGreenOnChange",
    "sendEventColorRedOnChange",
    "sendEventOnBlur",
    "sendEventOnChange",
    "sendEventOnClick",
    "sendEventOnFocus",
    "show",
    "size",
    "stretch",
    "tabIndex",
    "text-transform",
    "type",
    "validityChange",
    "value",
];
